apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webpage
  name: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - image: ashishizofficial/httpd_prac:${IMG_TAG}
        name: webpage
