apiVersion: v1
kind: Service
metadata:
  labels:
    app: webpage
  name: webpage
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30020
  selector:
    app: webpage
  type: NodePort
